app:
controller:
  admin:
    subject:
      default_per_page: 10
      default_page: 1
model:
  user:
    username:
      max_length: 30
      min_length: 6
    email:
      max_length: 50
    phone_number:
      max_length: 15
      min_length: 10
  course:
    name:
      max_length: 50
  task:
    step:
      greater_than: 0
    duration:
      greater_than: 0
view: