app:
controller:
  task:
    default_page: 1
    default_per_page: 20
    default_sort_by_column: :id
    default_sort_by_order: :asc
  admin:
    subject:
      default_per_page: 10
      default_page: 1
      default_sort_by_column: :id
      default_sort_by_order: :asc
    user:
      default_page: 1
      default_per_page: 10
    course:
      default_per_page: 10
      default_page: 1  
    task:
      default_page: 1
      default_per_page: 20
      default_sort_by_column: :id
      default_sort_by_order: :asc
model:
  user:
    username:
      max_length: 30
      min_length: 6
    email:
      max_length: 50
    phone_number:
      max_length: 15
      min_length: 10
  course:
    name:
      max_length: 50
  task:
    step:
      greater_than: 0
    duration:
      greater_than: 0
view: